# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartservice', '0002_auto_20161006_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='itemline',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cartservice.Order'),
        ),
    ]
