# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20161006_2358'),
        ('cartservice', '0006_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='member.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cartservice.PaymentMethod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
