# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartservice', '0008_auto_20161007_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemline',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartservice.Order'),
        ),
    ]
