# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designbottle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
