# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_auto_20161115_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='designbottle',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designbottle',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
