# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_auto_20161115_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Bottle'),
        ),
    ]
