# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_auto_20161118_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
