# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20161011_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='active',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
