# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20161011_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='active',
            new_name='is_active',
        ),
    ]
