# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.PositiveIntegerField(),
        ),
    ]
