# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20161004_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productchoice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductOption'),
        ),
    ]
