# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20161019_1246'),
        ('user', '0007_auto_20161019_1928'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0002_itemproperty_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PostalTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=13)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Order')),
            ],
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemline',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.ItemProperty'),
        ),
        migrations.AddField(
            model_name='itemline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
