# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20161019_1928'),
        ('trading', '0003_auto_20161019_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postaltrack',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Address'),
            preserve_default=False,
        ),
    ]
