# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20161019_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproperty',
            name='is_active',
        ),
    ]
