# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_itemline_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_track',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
    ]
