# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20161025_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transfer_slip',
            field=models.CharField(max_length=500),
        ),
    ]
