# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_auto_20161027_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproperty',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='itemproperty',
            name='option',
        ),
        migrations.RemoveField(
            model_name='postaltrack',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_update_date',
        ),
        migrations.DeleteModel(
            name='ItemProperty',
        ),
        migrations.DeleteModel(
            name='PostalTrack',
        ),
    ]
