# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_auto_20161108_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
