# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemline',
            name='status',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
