# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartservice', '0005_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
