# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartservice', '0009_auto_20161007_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slip',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='U', max_length=1),
        ),
    ]
