# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20161018_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductChocie',
            new_name='ProductChoice',
        ),
    ]
