# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_auto_20161108_1815'),
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productchoice',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductChoice',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
    ]
