# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
        ('product', '0017_remove_product_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='design.DesignBottle'),
        ),
    ]
