# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
